import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from backend.domain import models
from backend.infrastructure.database import Base, get_db
from backend.main import app

SQLALCHEMY_DATABASE_URL = "sqlite:///:memory:"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base.metadata.create_all(bind=engine)


def override_get_db():
    try:
        db = TestingSessionLocal()
        yield db
    finally:
        db.close()


client = TestClient(app)


@pytest.fixture(autouse=True)
def setup_db():
    app.dependency_overrides[get_db] = override_get_db
    db = TestingSessionLocal()
    db.query(models.EssentialNeighbor).delete()
    db.query(models.Hypothesis).delete()
    db.query(models.ObservationArtifact).delete()
    db.query(models.CorpusOccurrence).delete()
    db.query(models.IsolationEvent).delete()
    db.query(models.IsolationState).delete()
    db.query(models.ResearchRun).delete()
    db.commit()
    db.close()
    yield
    app.dependency_overrides.clear()


def test_slice_c_hypothesis_and_neighbor_flow():
    # The simplified contract keeps the free research flow (hypotheses,
    # falsification conditions, neighbor differentiation) but no longer routes
    # it through a LOCK gate or a gate-authorized claim-creation endpoint.
    run_id = "run_slice_c_fixture"
    db = TestingSessionLocal()
    db.add(
        models.ResearchRun(
            id=run_id,
            target_contract="ROOT_CORE",
            target_expression="ن ش ز",
            methodology_revision="v7.1-test-fixture",
            corpus_snapshot="snap1-test-fixture",
            authority_context={"profile": "test_fixture"},
        )
    )
    db.add(
        models.CorpusOccurrence(
            id="occ_c1",
            snapshot_id="snap1-test-fixture",
            expression="ن ش ز",
            verse_ref="58:11",
            text="انشزوا فانشزوا",
        )
    )
    db.commit()
    db.close()

    # Host-derived source-isolation preflight (a resumable checkpoint, not a gate).
    pre = client.post(f"/runs/{run_id}/blind/preflight")
    assert pre.status_code == 200

    # Hypothesis (H1) with a resolvable admitted-occurrence evidence reference.
    hyp_resp = client.post(
        f"/runs/{run_id}/hypotheses",
        json={
            "hypothesis_type": "H1",
            "target_contract": "ROOT_CORE",
            "scope": "All corpus occurrences",
            "statement": "Primary meaning is rising/elevation",
            "supporting_evidence_refs": ["occurrence:occ_c1"],
            "counterevidence_refs": [],
            "unresolved_cases": [],
            "rejection_condition": {
                "challenging_finding": "Finds a context where elevation is impossible",
                "search_location": "Corpus",
                "verification_method": "Syntactic check",
                "confounder_control": "Ensure it's not metaphorical",
                "failure_consequence": "Hypothesis falsified",
            },
            "provenance": "Generated by Steward",
        },
    )
    assert hyp_resp.status_code == 200
    hyp_id = hyp_resp.json()["id"]

    # A circular rejection condition is still rejected deterministically.
    circular_resp = client.post(
        f"/runs/{run_id}/hypotheses",
        json={
            "hypothesis_type": "H2",
            "target_contract": "ROOT_CORE",
            "scope": "All corpus occurrences",
            "statement": "Primary meaning is discord",
            "supporting_evidence_refs": [],
            "counterevidence_refs": [],
            "unresolved_cases": [],
            "rejection_condition": {
                "challenging_finding": "Reject if wrong",
                "search_location": "Any",
                "verification_method": "Check if it fails",
                "confounder_control": "None",
                "failure_consequence": "None",
            },
            "provenance": "Steward",
        },
    )
    assert circular_resp.status_code == 422
    assert "circular" in circular_resp.text.lower()

    # Essential Neighbor differentiation advances the run into CHALLENGE.
    nbr_resp = client.post(
        f"/hypotheses/{hyp_id}/neighbors",
        json={
            "shared_domain": "Physical movement",
            "positive_distinguishing_candidate": "ن ه ض",
            "relevant_differentiation_axes": ["Directionality", "Effort"],
            "substitution_probe": "Does substituting change meaning?",
            "boundary_negative_cases": [],
            "supporting_evidence": [],
            "counterevidence": [],
            "unresolved_distinction": "Slight overlap in physical elevation",
        },
    )
    assert nbr_resp.status_code == 200

    run_final = client.get(f"/runs/{run_id}")
    assert run_final.json()["current_stage"] == "CHALLENGE"


def test_hypothesis_rejects_unresolvable_cross_prefix_evidence():
    run_id = "run_slice_c_evidence"
    db = TestingSessionLocal()
    db.add(
        models.ResearchRun(
            id=run_id,
            target_contract="ROOT_CORE",
            target_expression="ن ش ز",
            methodology_revision="v7.1-test-fixture",
            corpus_snapshot="snap1-test-fixture",
            authority_context={"profile": "test_fixture"},
        )
    )
    db.commit()
    db.close()
    client.post(f"/runs/{run_id}/blind/preflight")

    # An occurrence reference that is absent from the run corpus cannot be invented.
    resp = client.post(
        f"/runs/{run_id}/hypotheses",
        json={
            "hypothesis_type": "H1",
            "target_contract": "ROOT_CORE",
            "scope": "All corpus occurrences",
            "statement": "Unsupported claim",
            "supporting_evidence_refs": ["occurrence:does_not_exist"],
            "counterevidence_refs": [],
            "unresolved_cases": [],
            "rejection_condition": {
                "challenging_finding": "A concrete falsifier",
                "search_location": "Corpus",
                "verification_method": "Structural check",
                "confounder_control": "Same form",
                "failure_consequence": "Hypothesis falsified",
            },
            "provenance": "Steward",
        },
    )
    assert resp.status_code == 422
    assert "absent or outside the run corpus" in resp.text
