import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from backend.domain import models
from backend.infrastructure.database import Base, get_db
from backend.main import app

SQLALCHEMY_DATABASE_URL = "sqlite:///:memory:"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base.metadata.create_all(bind=engine)


def override_get_db():
    try:
        db = TestingSessionLocal()
        yield db
    finally:
        db.close()


client = TestClient(app)


@pytest.fixture(autouse=True)
def setup_db():
    app.dependency_overrides[get_db] = override_get_db
    db = TestingSessionLocal()
    db.query(models.GateReport).delete()
    db.query(models.EssentialNeighbor).delete()
    db.query(models.Hypothesis).delete()
    db.query(models.ObservationArtifact).delete()
    db.query(models.IsolationEvent).delete()
    db.query(models.IsolationState).delete()
    db.query(models.ResearchRun).delete()
    db.commit()
    db.close()
    yield
    app.dependency_overrides.clear()


def test_slice_c_end_to_end():
    # 1. Setup Run and Blind Lab
    resp = client.post(
        "/runs",
        json={
            "target_contract": "ROOT_CORE",
            "target_expression": "ن ش ز",
            "methodology_revision": "v7.1",
            "corpus_snapshot": "snap1",
            "authority_context": {"initiator": "local_user"},
        },
    )
    run_id = resp.json()["id"]
    client.post(
        f"/runs/{run_id}/blind/preflight",
        json={
            "target_contract": "ROOT_CORE",
            "corpus_snapshot": "snap1",
            "methodology_reference": "ref_v1",
            "allowed_sources": ["QURAN_CORPUS"],
        },
    )

    # 2. Hypothesis (H1)
    hyp_resp = client.post(
        f"/runs/{run_id}/hypotheses",
        json={
            "hypothesis_type": "H1",
            "target_contract": "ROOT_CORE",
            "scope": "All corpus occurrences",
            "statement": "Primary meaning is rising/elevation",
            "supporting_evidence_refs": ["obs_1", "obs_2"],
            "counterevidence_refs": [],
            "unresolved_cases": [],
            "rejection_condition": {
                "challenging_finding": "Finds a context where elevation is impossible",
                "search_location": "Corpus",
                "verification_method": "Syntactic check",
                "confounder_control": "Ensure it's not metaphorical",
                "failure_consequence": "Hypothesis falsified",
            },
            "provenance": "Generated by Steward",
        },
    )
    assert hyp_resp.status_code == 200
    hyp_id = hyp_resp.json()["id"]

    # 3. Rejection Condition validation (Circular logic rejected)
    circular_resp = client.post(
        f"/runs/{run_id}/hypotheses",
        json={
            "hypothesis_type": "H2",
            "target_contract": "ROOT_CORE",
            "scope": "All corpus occurrences",
            "statement": "Primary meaning is discord",
            "supporting_evidence_refs": [],
            "counterevidence_refs": [],
            "unresolved_cases": [],
            "rejection_condition": {
                "challenging_finding": "Reject if wrong",
                "search_location": "Any",
                "verification_method": "Check if it fails",
                "confounder_control": "None",
                "failure_consequence": "None",
            },
            "provenance": "Steward",
        },
    )
    assert circular_resp.status_code == 422
    assert "circular" in circular_resp.text.lower()

    # 4. Essential Neighbor
    nbr_resp = client.post(
        f"/hypotheses/{hyp_id}/neighbors",
        json={
            "shared_domain": "Physical movement",
            "positive_distinguishing_candidate": "ن ه ض",
            "relevant_differentiation_axes": ["Directionality", "Effort"],
            "substitution_probe": "Does substituting change meaning?",
            "boundary_negative_cases": [],
            "supporting_evidence": [],
            "counterevidence": [],
            "unresolved_distinction": "Slight overlap in physical elevation",
        },
    )
    assert nbr_resp.status_code == 200

    # 5. Gate Report (Failed INTERNAL_LOCK) for {ن ش ز}
    gate_resp = client.post(
        f"/runs/{run_id}/gates",
        json={
            "gate_code": "INTERNAL_LOCK",
            "status": "FAILED",
            "evidence_refs": [hyp_id],
            "evaluated_revision": "v1",
            "failure_reason": "Insufficient distinguishing evidence",
        },
    )
    assert gate_resp.status_code == 200

    # 6. Verify SemanticClaim generation is blocked because gate failed
    claim_resp = client.post(
        f"/runs/{run_id}/claims",
        json={"contract_type": "ROOT_CORE", "research_run_id": run_id},
    )
    assert claim_resp.status_code == 403
    assert "not passed" in claim_resp.text

    # 7. Check Run status is LOCK_BLOCKED
    run_final = client.get(f"/runs/{run_id}")
    assert run_final.json()["status"] == "LOCK_BLOCKED"
