"""Initial schema

Revision ID: 80330541af56
Revises: 
Create Date: 2026-08-22 16:46:24.493320

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80330541af56'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('corpus_occurrences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('expression', sa.String(), nullable=True),
    sa.Column('verse_ref', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_occurrences_id'), 'corpus_occurrences', ['id'], unique=False)
    op.create_index(op.f('ix_corpus_occurrences_snapshot_id'), 'corpus_occurrences', ['snapshot_id'], unique=False)
    op.create_table('corpus_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_text_source', sa.String(), nullable=False),
    sa.Column('canonical_text_version', sa.String(), nullable=False),
    sa.Column('canonical_text_hash', sa.String(), nullable=False),
    sa.Column('structural_source', sa.String(), nullable=True),
    sa.Column('structural_source_version', sa.String(), nullable=True),
    sa.Column('import_revision', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_snapshots_id'), 'corpus_snapshots', ['id'], unique=False)
    op.create_table('governance_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_index(op.f('ix_governance_rules_id'), 'governance_rules', ['id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_contract', sa.String(), nullable=False),
    sa.Column('target_expression', sa.String(), nullable=False),
    sa.Column('methodology_revision', sa.String(), nullable=False),
    sa.Column('corpus_snapshot', sa.String(), nullable=False),
    sa.Column('authority_context', sa.JSON(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_id'), 'research_runs', ['id'], unique=False)
    op.create_table('steward_commands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('evaluated_rules', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steward_commands_id'), 'steward_commands', ['id'], unique=False)
    op.create_table('ai_execution_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('analysis_stage', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('skill_version', sa.String(), nullable=True),
    sa.Column('prompt_revision', sa.String(), nullable=True),
    sa.Column('tools_available', sa.JSON(), nullable=True),
    sa.Column('input_artifact_refs', sa.JSON(), nullable=True),
    sa.Column('output_artifact_refs', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_execution_records_id'), 'ai_execution_records', ['id'], unique=False)
    op.create_table('change_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('proposed_changes', sa.String(), nullable=True),
    sa.Column('impact_analysis', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_code'], ['governance_rules.rule_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_proposals_id'), 'change_proposals', ['id'], unique=False)
    op.create_table('gate_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('gate_code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('evaluated_revision', sa.String(), nullable=True),
    sa.Column('required_action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_reports_id'), 'gate_reports', ['id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('hypothesis_type', sa.String(), nullable=True),
    sa.Column('target_contract', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('supporting_evidence_refs', sa.JSON(), nullable=True),
    sa.Column('counterevidence_refs', sa.JSON(), nullable=True),
    sa.Column('unresolved_cases', sa.JSON(), nullable=True),
    sa.Column('rejection_condition', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_id'), 'hypotheses', ['id'], unique=False)
    op.create_table('isolation_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('attempted_action', sa.String(), nullable=True),
    sa.Column('was_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isolation_events_id'), 'isolation_events', ['id'], unique=False)
    op.create_table('isolation_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('target_contract', sa.String(), nullable=True),
    sa.Column('corpus_snapshot', sa.String(), nullable=True),
    sa.Column('methodology_reference', sa.String(), nullable=True),
    sa.Column('allowed_sources', sa.JSON(), nullable=True),
    sa.Column('is_contaminated', sa.String(), nullable=True),
    sa.Column('contamination_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_run_id')
    )
    op.create_index(op.f('ix_isolation_states_id'), 'isolation_states', ['id'], unique=False)
    op.create_table('observation_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('occurrence_ref', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('syntax', sa.String(), nullable=True),
    sa.Column('participant_roles', sa.String(), nullable=True),
    sa.Column('local_context', sa.String(), nullable=True),
    sa.Column('unresolved_ambiguity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_artifacts_id'), 'observation_artifacts', ['id'], unique=False)
    op.create_table('rule_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('changes_described', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_code'], ['governance_rules.rule_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_revisions_id'), 'rule_revisions', ['id'], unique=False)
    op.create_table('semantic_claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('epistemic_state', sa.String(), nullable=True),
    sa.Column('review_state', sa.String(), nullable=True),
    sa.Column('freshness_state', sa.String(), nullable=True),
    sa.Column('publication_state', sa.String(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('index_coverage', sa.String(), nullable=True),
    sa.Column('deep_analysis_coverage', sa.String(), nullable=True),
    sa.Column('abstract_root_core', sa.String(), nullable=True),
    sa.Column('root_definition', sa.String(), nullable=True),
    sa.Column('root_meaning', sa.String(), nullable=True),
    sa.Column('root_concept', sa.String(), nullable=True),
    sa.Column('rejection_condition', sa.String(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('counterevidence', sa.JSON(), nullable=True),
    sa.Column('unresolved_cases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_claims_id'), 'semantic_claims', ['id'], unique=False)
    op.create_table('dependency_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dependent_claim_id', sa.String(), nullable=True),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('dependency_ref', sa.String(), nullable=False),
    sa.Column('dependency_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_claim_id'], ['semantic_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_records_id'), 'dependency_records', ['id'], unique=False)
    op.create_table('essential_neighbors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('shared_domain', sa.String(), nullable=True),
    sa.Column('positive_distinguishing_candidate', sa.String(), nullable=True),
    sa.Column('relevant_differentiation_axes', sa.JSON(), nullable=True),
    sa.Column('substitution_probe', sa.String(), nullable=True),
    sa.Column('boundary_negative_cases', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('counterevidence', sa.JSON(), nullable=True),
    sa.Column('unresolved_distinction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essential_neighbors_id'), 'essential_neighbors', ['id'], unique=False)
    op.create_table('quality_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('purity_score', sa.Integer(), nullable=True),
    sa.Column('synthetic_data_leak', sa.Boolean(), nullable=True),
    sa.Column('external_data_leak', sa.Boolean(), nullable=True),
    sa.Column('corpus_coverage', sa.Integer(), nullable=True),
    sa.Column('deep_analysis_coverage', sa.Integer(), nullable=True),
    sa.Column('reproducibility_score', sa.Integer(), nullable=True),
    sa.Column('unresolved_conflict_burden', sa.Integer(), nullable=True),
    sa.Column('methodological_purity_flags', sa.JSON(), nullable=True),
    sa.Column('evaluation_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['semantic_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_profiles_id'), 'quality_profiles', ['id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('reviewer_identity', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('evaluated_claim_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['semantic_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_id'), 'review_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_decisions_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_quality_profiles_id'), table_name='quality_profiles')
    op.drop_table('quality_profiles')
    op.drop_index(op.f('ix_essential_neighbors_id'), table_name='essential_neighbors')
    op.drop_table('essential_neighbors')
    op.drop_index(op.f('ix_dependency_records_id'), table_name='dependency_records')
    op.drop_table('dependency_records')
    op.drop_index(op.f('ix_semantic_claims_id'), table_name='semantic_claims')
    op.drop_table('semantic_claims')
    op.drop_index(op.f('ix_rule_revisions_id'), table_name='rule_revisions')
    op.drop_table('rule_revisions')
    op.drop_index(op.f('ix_observation_artifacts_id'), table_name='observation_artifacts')
    op.drop_table('observation_artifacts')
    op.drop_index(op.f('ix_isolation_states_id'), table_name='isolation_states')
    op.drop_table('isolation_states')
    op.drop_index(op.f('ix_isolation_events_id'), table_name='isolation_events')
    op.drop_table('isolation_events')
    op.drop_index(op.f('ix_hypotheses_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_gate_reports_id'), table_name='gate_reports')
    op.drop_table('gate_reports')
    op.drop_index(op.f('ix_change_proposals_id'), table_name='change_proposals')
    op.drop_table('change_proposals')
    op.drop_index(op.f('ix_ai_execution_records_id'), table_name='ai_execution_records')
    op.drop_table('ai_execution_records')
    op.drop_index(op.f('ix_steward_commands_id'), table_name='steward_commands')
    op.drop_table('steward_commands')
    op.drop_index(op.f('ix_research_runs_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_governance_rules_id'), table_name='governance_rules')
    op.drop_table('governance_rules')
    op.drop_index(op.f('ix_corpus_snapshots_id'), table_name='corpus_snapshots')
    op.drop_table('corpus_snapshots')
    op.drop_index(op.f('ix_corpus_occurrences_snapshot_id'), table_name='corpus_occurrences')
    op.drop_index(op.f('ix_corpus_occurrences_id'), table_name='corpus_occurrences')
    op.drop_table('corpus_occurrences')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
