"""Add AIExecutionRecord

Revision ID: 5542b3a62e23
Revises: fe97644812d6
Create Date: 2026-08-22 06:41:44.317651

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5542b3a62e23"
down_revision: str | None = "fe97644812d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_execution_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("research_run_id", sa.String(), nullable=False),
        sa.Column("analysis_stage", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("skill_version", sa.String(), nullable=True),
        sa.Column("prompt_revision", sa.String(), nullable=True),
        sa.Column("tools_available", sa.JSON(), nullable=True),
        sa.Column("input_artifact_refs", sa.JSON(), nullable=True),
        sa.Column("output_artifact_refs", sa.JSON(), nullable=True),
        sa.Column("execution_status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_execution_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_execution_records_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_execution_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_execution_records_id"))

    op.drop_table("ai_execution_records")
    # ### end Alembic commands ###
