"""Initial migration

Revision ID: a6b241ebe53d
Revises:
Create Date: 2026-08-22 06:12:32.764927

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6b241ebe53d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("target_contract", sa.String(), nullable=False),
        sa.Column("target_expression", sa.String(), nullable=False),
        sa.Column("methodology_revision", sa.String(), nullable=False),
        sa.Column("corpus_snapshot", sa.String(), nullable=False),
        sa.Column("authority_context", sa.JSON(), nullable=False),
        sa.Column("current_stage", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_runs_id"), "research_runs", ["id"], unique=False)
    op.create_table(
        "gate_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("research_run_id", sa.String(), nullable=True),
        sa.Column("gate_code", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("evaluated_revision", sa.String(), nullable=True),
        sa.Column("required_action", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gate_reports_id"), "gate_reports", ["id"], unique=False)
    op.create_table(
        "semantic_claims",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("research_run_id", sa.String(), nullable=True),
        sa.Column("contract_type", sa.String(), nullable=False),
        sa.Column("official_status", sa.String(), nullable=True),
        sa.Column("index_coverage", sa.String(), nullable=True),
        sa.Column("deep_analysis_coverage", sa.String(), nullable=True),
        sa.Column("abstract_root_core", sa.String(), nullable=True),
        sa.Column("root_definition", sa.String(), nullable=True),
        sa.Column("root_meaning", sa.String(), nullable=True),
        sa.Column("root_concept", sa.String(), nullable=True),
        sa.Column("rejection_condition", sa.String(), nullable=True),
        sa.Column("supporting_evidence", sa.JSON(), nullable=True),
        sa.Column("counterevidence", sa.JSON(), nullable=True),
        sa.Column("unresolved_cases", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_semantic_claims_id"), "semantic_claims", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_semantic_claims_id"), table_name="semantic_claims")
    op.drop_table("semantic_claims")
    op.drop_index(op.f("ix_gate_reports_id"), table_name="gate_reports")
    op.drop_table("gate_reports")
    op.drop_index(op.f("ix_research_runs_id"), table_name="research_runs")
    op.drop_table("research_runs")
    # ### end Alembic commands ###
