"""Add missing tables for F1 remediation

Revision ID: d7e1917cbc59
Revises: 5542b3a62e23
Create Date: 2026-08-23 20:49:45.653575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e1917cbc59'
down_revision: Union[str, None] = '5542b3a62e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('corpus_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_text_source', sa.String(), nullable=False),
    sa.Column('canonical_text_version', sa.String(), nullable=False),
    sa.Column('canonical_text_hash', sa.String(), nullable=False),
    sa.Column('structural_source', sa.String(), nullable=True),
    sa.Column('structural_source_version', sa.String(), nullable=True),
    sa.Column('import_revision', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpus_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_snapshots_id'), ['id'], unique=False)

    op.create_table('governance_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    with op.batch_alter_table('governance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_rules_id'), ['id'], unique=False)

    op.create_table('steward_commands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('evaluated_rules', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steward_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steward_commands_id'), ['id'], unique=False)

    op.create_table('change_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('proposed_changes', sa.String(), nullable=True),
    sa.Column('impact_analysis', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_code'], ['governance_rules.rule_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_proposals_id'), ['id'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('hypothesis_type', sa.String(), nullable=True),
    sa.Column('target_contract', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('supporting_evidence_refs', sa.JSON(), nullable=True),
    sa.Column('counterevidence_refs', sa.JSON(), nullable=True),
    sa.Column('unresolved_cases', sa.JSON(), nullable=True),
    sa.Column('rejection_condition', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_id'), ['id'], unique=False)

    op.create_table('isolation_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('attempted_action', sa.String(), nullable=True),
    sa.Column('was_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('isolation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_isolation_events_id'), ['id'], unique=False)

    op.create_table('rule_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('changes_described', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_code'], ['governance_rules.rule_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_revisions_id'), ['id'], unique=False)

    op.create_table('dependency_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dependent_claim_id', sa.String(), nullable=True),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('dependency_ref', sa.String(), nullable=False),
    sa.Column('dependency_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_claim_id'], ['semantic_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependency_records_id'), ['id'], unique=False)

    op.create_table('essential_neighbors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('shared_domain', sa.String(), nullable=True),
    sa.Column('positive_distinguishing_candidate', sa.String(), nullable=True),
    sa.Column('relevant_differentiation_axes', sa.JSON(), nullable=True),
    sa.Column('substitution_probe', sa.String(), nullable=True),
    sa.Column('boundary_negative_cases', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('counterevidence', sa.JSON(), nullable=True),
    sa.Column('unresolved_distinction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('essential_neighbors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essential_neighbors_id'), ['id'], unique=False)

    op.create_table('quality_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('purity_score', sa.Integer(), nullable=True),
    sa.Column('purity_rating', sa.String(), nullable=True),
    sa.Column('purity_findings', sa.JSON(), nullable=True),
    sa.Column('synthetic_data_leak', sa.Boolean(), nullable=True),
    sa.Column('external_data_leak', sa.Boolean(), nullable=True),
    sa.Column('corpus_coverage', sa.Integer(), nullable=True),
    sa.Column('deep_analysis_coverage', sa.Integer(), nullable=True),
    sa.Column('reproducibility_score', sa.Integer(), nullable=True),
    sa.Column('unresolved_conflict_burden', sa.Integer(), nullable=True),
    sa.Column('methodological_purity_flags', sa.JSON(), nullable=True),
    sa.Column('evaluation_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['semantic_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_profiles_id'), ['id'], unique=False)

    op.create_table('review_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('reviewer_identity', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('evaluated_claim_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['semantic_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_id'), ['id'], unique=False)

    with op.batch_alter_table('gate_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_refs', sa.JSON(), nullable=True))

    with op.batch_alter_table('semantic_claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epistemic_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('review_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('freshness_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('publication_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('revision_id', sa.Integer(), nullable=True))
        batch_op.drop_column('official_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semantic_claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('revision_id')
        batch_op.drop_column('publication_state')
        batch_op.drop_column('freshness_state')
        batch_op.drop_column('review_state')
        batch_op.drop_column('epistemic_state')

    with op.batch_alter_table('gate_reports', schema=None) as batch_op:
        batch_op.drop_column('evidence_refs')

    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('quality_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_profiles_id'))

    op.drop_table('quality_profiles')
    with op.batch_alter_table('essential_neighbors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essential_neighbors_id'))

    op.drop_table('essential_neighbors')
    with op.batch_alter_table('dependency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependency_records_id'))

    op.drop_table('dependency_records')
    with op.batch_alter_table('rule_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_revisions_id'))

    op.drop_table('rule_revisions')
    with op.batch_alter_table('isolation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_isolation_events_id'))

    op.drop_table('isolation_events')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_id'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('change_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_proposals_id'))

    op.drop_table('change_proposals')
    with op.batch_alter_table('steward_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steward_commands_id'))

    op.drop_table('steward_commands')
    with op.batch_alter_table('governance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_rules_id'))

    op.drop_table('governance_rules')
    with op.batch_alter_table('corpus_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_snapshots_id'))

    op.drop_table('corpus_snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
