"""Blind Lab isolation tables

Revision ID: dab520d032b0
Revises: a6b241ebe53d
Create Date: 2026-08-22 06:18:54.362738

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dab520d032b0"
down_revision: str | None = "a6b241ebe53d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corpus_occurrences",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=True),
        sa.Column("expression", sa.String(), nullable=True),
        sa.Column("verse_ref", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corpus_occurrences_id"), "corpus_occurrences", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_corpus_occurrences_snapshot_id"),
        "corpus_occurrences",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "isolation_states",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("research_run_id", sa.String(), nullable=True),
        sa.Column("target_contract", sa.String(), nullable=True),
        sa.Column("corpus_snapshot", sa.String(), nullable=True),
        sa.Column("methodology_reference", sa.String(), nullable=True),
        sa.Column("allowed_sources", sa.JSON(), nullable=True),
        sa.Column("is_contaminated", sa.String(), nullable=True),
        sa.Column("contamination_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("research_run_id"),
    )
    op.create_index(
        op.f("ix_isolation_states_id"), "isolation_states", ["id"], unique=False
    )
    op.create_table(
        "observation_artifacts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("research_run_id", sa.String(), nullable=True),
        sa.Column("occurrence_ref", sa.String(), nullable=False),
        sa.Column("form", sa.String(), nullable=True),
        sa.Column("syntax", sa.String(), nullable=True),
        sa.Column("participant_roles", sa.String(), nullable=True),
        sa.Column("local_context", sa.String(), nullable=True),
        sa.Column("unresolved_ambiguity", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observation_artifacts_id"),
        "observation_artifacts",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_observation_artifacts_id"), table_name="observation_artifacts"
    )
    op.drop_table("observation_artifacts")
    op.drop_index(op.f("ix_isolation_states_id"), table_name="isolation_states")
    op.drop_table("isolation_states")
    op.drop_index(
        op.f("ix_corpus_occurrences_snapshot_id"), table_name="corpus_occurrences"
    )
    op.drop_index(op.f("ix_corpus_occurrences_id"), table_name="corpus_occurrences")
    op.drop_table("corpus_occurrences")
    # ### end Alembic commands ###
